#1	1230453	.	TCA	T	99	PASS	DP=100;LEN=2;TYPE=DEL;TRANSCRIPT=NM_080605.1;TRANSCRIPT_POS=42;CIGAR:27S11=1X1=1X1=2D3=1X4=1X2=1X1=1X3=1X3=1X2=678N8=1099N1X19=1X566=1X490=1D499=1X276=;GENOME_REF=NC_000001.11
#NM_080605.1	0	NC_000001.11	1230438	255	27S 11= 1X 1= 1X 1= 2D 3=1X4=1X2=1X1=1X3=1X3=1X2=678N8=1099N1X19=1X566=1X490=1D499=1X276=	*	0	0	ATAGCCACATCCCTGAATGTCACCTGTCCCTGGGTGAGAGCCATGCCTGACTTGTCTTTCTTTCCTCTTCCTCTTCCGGCGCGGGCGCCATGAATCTGCTGCGGCGGGCGTGGCGGCGGCGGGCGGCGCTAGGCCTGGGCACGCTGGCGCTGTGCGGGGCGGCGCTGCTCTACCTGGCGCGCTGCGCGGCCGAGCCCGGGGACCCCAGGGCGATGTCGGGCCGCAGCCCGCCTCCCCCCGCGCCCGCGCGCGCCGCCGCCTTCCTGGCAGTGCTGGTGGCCAGCGCGCCCCGCGCCGCCGAGCGCCGCAGCGTGATCCGCAGCACGTGGCTTGCGCGGCGCGGGGCCCCGGGCGACGTGTGGGCGCGCTTTGCCGTGGGCACGGCCGGCCTGGGCGCCGAGGAGCGGCGCGCCCTGGAGCGGGAGCAGGCGCGGCACGGGGACCTGCTGCTGCTGCCCGCGCTGCGCGACGCCTACGAAAACCTCACGGCCAAGGTGCTGGCCATGCTGGCCTGGCTGGACGAGCACGTGGCCTTCGAGTTCGTGCTCAAGGCGGACGACGACTCCTTCGCGCGGCTGGACGCGCTGCTGGCCGAGCTGCGCGCCCGCGAGCCCGCGCGCCGCCGCCGCCTCTACTGGGGCTTCTTCTCGGGCCGCGGCCGAGTCAAGCCGGGGGGGCGCTGGCGCGAGGCCGCCTGGCAACTCTGCGACTACTACCTGCCCTACGCGCTGGGCGGCGGCTACGTGCTCTCGGCCGACCTGGTGCACTACCTGCGCCTCAGCCGCGACTACCTGCGCGCCTGGCACAGCGAGGACGTGTCTCTGGGCGCCTGGCTGGCGCCGGTGGACGTCCAGCGGGAGCACGACCCGCGCTTCGACACCGAATACCGGTCCCGCGGCTGCAGCAACCAGTACCTGGTGACGCACAAGCAGAGCCTGGAGGACATGCTGGAGAAGCACGCGACGCTGGCGCGCGAGGGCCGCCTGTGCAAGCGCGAGGTGCAGCTGCGCCTGTCCTACGTGTACGACTGGTCCGCGCCGCCCTCGCAGTGCTGCCAGAGAAGGGAGGGCATCCCCTGAGCCGCCGCGGCCCGGCCCTCCGGGACACCTGCTTCACCCGGCGGCGCCTTGGGGCAGGTGCCGAGCGGGCGCATACGCCCGGGCCCCAAGGCCCCCGTCCCGCAGCCACGCTTGTGGTCGCTGCGTCCCGGTCTGCGTTTGGGAGACCCCTGGGGGTTGCCGGGGCAGCGCGCCGTGTCCAGGTGGAGGTGCCCGTTCCTGGACCTCAGCGAGCCTGAGCCGGGCCCGGCCGCACGCTGACCCCCGTGCTGTCCCCGACCGGCTCACGGGGCTGGGCTCCGATCTTCCGTGTCTCTTATCAGTGGCGTTTCTCACGTCTGCGTCTCAGATCTAACGTGGTTTCACATCAATCCGCTTTCATGGGATTTTGGTCTCTGTCCAGTGACTTCGTGGTAAATGTAACTCAGTGTTTGCTTGCGACTTATTTATAAATATTGTAAGTTTGTGTCGATGAGTGTAAGTTGGCAGTGCGCACGTCTCGGTTTTTTTACATGATTTAAGGAAAGACTTTTATGTCAGAACTTGGTGCCTGTACCGTCAACCCCGCTGCTGCCCGTGTTTAAACGCAGGAGCACTTTAAAACTGGCCATCTATCTTTTCAGTGTACAAGTCACTGAACCCATTGTTTCTTTCTGAAGAGACTTTCCTTTCAAGGCTTCCCATGGGTCCGCGCCACACAGGGCCGGTGCTGCTTTATTTCAGACTCTGCCCCAGGTTCCAGGAATCCGAACCCCGGAGTGCTGACGCGGTTCCCCAACTTCCGCCTTAAGAAAACAGGACCAGCCGGCACCAGGCCCGTCTCTCACGTACTTTAACACATCCTTGAAAGCCCCTCGTTTAATGAGAAAA	*	MD:Z:11G1G1^TC3T4T2T1T3T3T10C19G566C490^C499A276	NH:i:1	NM:i:42	XM:i:12	XO:i:3	XG:i:30	XS:A:+

# print(find_substring_positions(Fasta, pattern))
#fa = "ATAGCCACATCCCTGAATGTCACCTGT  CCCTGGGTGAG(11=)  A(X) G(=) C(X)  C(=) ATGCCTGACTTGTCTTTCTTTCCTCTTCCTCTTCCGGCGCGGGCG"

#eq11 = "CCCTGGGTGAG AG"
#r_1230423_1230463= "CCCCAAGGAAGGAAA CCCTGGGTGAG  G(1x) G(1=) G(x) C(=) TC(2D) ATGTCTGAT"
#sub = "CCCTGGGTGAG"
sub = "CAT"
fa = "ATAGCCACATCCCTGAATGTCACCTGTCCCTGGGTGAGAGCCATGCCTGACTTGTCTTTCTTTCCTCTTCCTCTTCCGGCGCGGGCG"
def find_substring_positions(string, substring):
    positions = []
    start = 0
    while True:
        start = string.find(substring, start)
        if start == -1:
            break
        positions.append(start)
        start += 1  # Move to the next character after the current found substring
    return positions

print(find_substring_positions(fa, sub))
print(fa[42])